### ISSUE TITLE
Add basic animations to the UI

### ISSUE THREAD

**Issue by aaryak-shah** [aaryak-shah/git-init-FOSS#1]
Add a few animations to some actions such as hovering on a card or a button. Keep it simple.

**Comment by AmanPachori** [comment]
@aaryak-shah Can you please elaborate that what kind of animation is to be added

**Comment by aaryak-shah** [comment]
@AmanPachori Fairly simple things, for example if I hover on the footer buttons it could fade between the white and green colors instead of switching instantly. Similarly with the border on project cards.

Other than this you can try and use your judgement and creativity to add animations whenever it feels relevant. Try to keep it minimal though.

Hold working this until issue #5 is resolved. I will assign after that.

**Comment by AmanPachori** [comment]
Ok sir I will work on this

**Comment by harshgupta1249** [comment]
@aaryak-shah If this issue is available, I would like to work on it.

**Comment by AmanPachori** [comment]
@harshgupta1249  is I am working on this

**Comment by aaryak-shah** [comment]
@AmanPachori @harshgupta1249 assigning to both. Ensure that your work is compatible with the latest commit.
