### ISSUE TITLE
[DOCUMENTATION] Update Readme

### ISSUE THREAD

**Issue by kunaljain0212** [aaryak-shah/git-init-FOSS#14]
The readme should contain the following details:
 
1. Title of the project
2. Brief description of the project
3. Screenshots of the project
3. Main features implemented in the project
4. Tech Stack and APIs used
5. Hosted link of the project
6. Setup steps
7. Contributors section
7. Social media handles of AASF

**Comment by AmanPachori** [comment]
@kunaljain0212  sir I would like to work on this

**Comment by kunaljain0212** [comment]
Sure go ahead @AmanPachori!

**Comment by AmanPachori** [comment]
@kunaljain0212 sir can you guide me little bit about what write in Brief description of the project and main features implemented.

**Comment by kunaljain0212** [comment]
I think we can leave the description header as of now. In the main features header, you can write about the project cards and the information they are displaying, the search functionality, dynamic fetching of scores and updation of the leaderboard.

**Comment by kunaljain0212** [comment]
#15
