### ISSUE TITLE
Capitalize roll numbers of students on the leaderboard

### ISSUE THREAD

**Issue by hs2361** [aaryak-shah/git-init-FOSS#16]
Currently, the roll numbers of users on the leaderboard are displayed with different capitalizations. For example, one of the students has a roll number "2020bcs-079" and the others have "2020BCS-036" in uppercase. There may also be roll numbers in mixed cases. This can be easily fixed by changing the roll number to uppercase.

**Comment by moazfarrukh** [comment]
can this be assigned to me

**Comment by AmanPachori** [comment]
@hs2361 can I work on this

**Comment by IshaSah** [comment]
please assign this issue to me, I can fix this

**Comment by SahilSatyam** [comment]
please assign this to me, i'll resolve this.

**Comment by hs2361** [comment]
@moazfarrukh @IshaSah @SahilSatyam Hi and thank you for willing to contribute! Unfortunately this website is for the git-init-FOSS event, and contributions are currently only open for students of IIITM, so I am unable to assign this issue to you.
