### ISSUE TITLE
Change ranking criteria for leaderboard

### ISSUE THREAD

**Issue by hs2361** [aaryak-shah/git-init-FOSS#18]
With PR kunaljain0212/git-init-FOSS-API#2 merged, the API returns the number of easy, medium and hard issues that a student has resolved. Our current ranking system ranks on the basis of the total score, and in case of a tie, the students are sorted in alphabetical order. However, with the newly added data about the different types of issues and their numbers we can make our ranking system a lot better.

We need to rank students according to the following criteria, in that order (i.e. lowest criterion gets the lowest precedence):
* Total score
* Number of hard issues solved
* Number of medium issues solved
* Number of easy issues solved
* Alphabetical order of name

With this system, in case of a tie, the student who has solved more difficult issues will be ranked higher.

**Comment by kunaljain0212** [comment]
Sure go ahead @sahil-mittal! 🚀
