### ISSUE TITLE
Add dynamic fetching of profile avatars

### ISSUE THREAD

**Issue by aaryak-shah** [aaryak-shah/git-init-FOSS#2]
The avatars displayed on the project cards are hardcoded into a JSON array which you can find in `src/stores/avatars.js`. Currently this list has to be manually updated every time a new project, and thus a new maintainer is added to the event.
Make a javascript function to fetch the same data dynamically from `https://api.github.com/users/profilename`, so as to automatically account for any new maintainer's profile.

**Comment by sohan2410** [comment]
Can I work on this issue?

**Comment by aaryak-shah** [comment]
Sure! Feel free to ask here if you have any queries
