### ISSUE TITLE
Fix icons not recieving color bug

### ISSUE THREAD

**Issue by aaryak-shah** [aaryak-shah/git-init-FOSS#3]
Icons used in this project `[GitHub, Instagram, Facebook, Medium, Linkedin, Hamburger Menu, Chevron Up]` are provided by the `svelte-icons` package, available [here](https://www.npmjs.com/package/svelte-icons)

Icons are not displaying any color provided to them in CSS, and are always displayed in white. The requirement is for the icons to follow the style color that has been programmed.

**Comment by tm2k23** [comment]
Hey @aaryak-shah can u please assign me this, I will fix it

**Comment by aaryak-shah** [comment]
@tm2k23 Hi and thank you for willing to contribute! Unfortunately this website is for the git-init-FOSS event, and contributions are currently only open for students of IIITM, so I am unable to assign this issue to you.

**Comment by AmanPachori** [comment]
Hey @aaryak-shah sir can you please assign me, I will fix it.

**Comment by aaryak-shah** [comment]
@AmanPachori yes sure. Feel free to ask here if you have any questions.

**Comment by AmanPachori** [comment]
@aaryak-shah  sir I have make PR of this is Issue

**Comment by aaryak-shah** [comment]
Your PR has been merged
