### ISSUE TITLE
Fix styling on leaderboard profile links

### ISSUE THREAD

**Issue by aaryak-shah** [aaryak-shah/git-init-FOSS#5]
Anchor tags used in the leaderboard entries must be colored white

**Comment by harshgupta1249** [comment]
Can I work on this issue ? @aaryak-shah

**Comment by kunaljain0212** [comment]
Sure go ahead @harshgupta1249!

**Comment by harshgupta1249** [comment]
is the requirement only to make the color of the link white ?

**Comment by aaryak-shah** [comment]
@harshgupta1249 yes
