### ISSUE TITLE
[FEATURE] Display contestant avatars in the leaderboard

### ISSUE THREAD

**Issue by kunaljain0212** [aaryak-shah/git-init-FOSS#9]
Avatars are GitHub profile pictures in general terms. GitHub provides an API for dynamically fetching the avatar of a specific user ``https://avatars.githubusercontent.com/{username}``. Using this API create avatar chips in the leaderboard similar to project cards and dynamically fetch and display avatars for each contestant.

**Comment by AmanPachori** [comment]
@kunaljain0212  Sir I would like to work on this

**Comment by kunaljain0212** [comment]
Sure go ahead @AmanPachori! 🚀
